"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-04

Hand-written (not autogenerated) to match app/models/*.py exactly, since
no live Postgres was available to diff against when this was authored.
Table order respects FK dependencies; downgrade() drops in reverse.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pg

# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

EMBEDDING_DIM = 1536  # keep in sync with app/models/cache_entries.py


def upgrade() -> None:
    # pgvector must exist before cache_entries.embedding (Vector type) is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "users",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("sso_identity", sa.JSON(), nullable=True),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index("ix_users_email", "users", ["email"])

    op.create_table(
        "providers",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("slug", sa.String(64), nullable=False),
        sa.UniqueConstraint("name", name="uq_providers_name"),
        sa.UniqueConstraint("slug", name="uq_providers_slug"),
    )
    op.create_index("ix_providers_slug", "providers", ["slug"])

    op.create_table(
        "projects",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", pg.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("policy_id", pg.UUID(as_uuid=True), nullable=True),
        sa.Column("retention", sa.Integer(), nullable=False, server_default="0"),
        sa.CheckConstraint("retention >= 0", name="ck_project_retention_nonneg"),
    )
    op.create_index("ix_projects_user_id", "projects", ["user_id"])

    op.create_table(
        "models",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provider_id", pg.UUID(as_uuid=True), sa.ForeignKey("providers.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("context_window", sa.Integer(), nullable=False),
        sa.CheckConstraint("context_window > 0", name="ck_model_context_window_positive"),
    )
    op.create_index("ix_models_provider_id", "models", ["provider_id"])

    op.create_table(
        "api_keys",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "project_id", pg.UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("key_hash", sa.String(255), nullable=False),
        sa.Column("prefix", sa.String(16), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("key_hash", name="uq_api_keys_key_hash"),
    )
    op.create_index("ix_api_keys_project_id", "api_keys", ["project_id"])
    op.create_index("ix_api_keys_prefix", "api_keys", ["prefix"])

    op.create_table(
        "model_prices",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_id", pg.UUID(as_uuid=True), sa.ForeignKey("models.id", ondelete="CASCADE"), nullable=False),
        sa.Column("prices", sa.JSON(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_model_prices_model_id", "model_prices", ["model_id"])

    op.create_table(
        "model_metrics",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_id", pg.UUID(as_uuid=True), sa.ForeignKey("models.id", ondelete="CASCADE"), nullable=False),
        sa.Column("window", sa.String(32), nullable=False),
        sa.Column("latency", sa.Float(), nullable=False),
        sa.Column("ttft", sa.Float(), nullable=False),
        sa.Column("error_rate", sa.Float(), nullable=False),
        sa.Column("quality", sa.Float(), nullable=False),
        sa.CheckConstraint("error_rate >= 0 AND error_rate <= 1", name="ck_model_metrics_error_rate_range"),
        sa.CheckConstraint("quality >= 0 AND quality <= 1", name="ck_model_metrics_quality_range"),
    )
    op.create_index("ix_model_metrics_model_id", "model_metrics", ["model_id"])

    op.create_table(
        "requests",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "project_id", pg.UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("model_id", pg.UUID(as_uuid=True), sa.ForeignKey("models.id", ondelete="SET NULL"), nullable=True),
        sa.Column("model", sa.String(255), nullable=False),
        sa.Column(
            "provider_id", pg.UUID(as_uuid=True), sa.ForeignKey("providers.id", ondelete="SET NULL"), nullable=True
        ),
        sa.Column("provider", sa.String(255), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(32), nullable=False, server_default="pending"),
        sa.Column("input_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("output_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("total_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("cost", sa.Float(), nullable=False, server_default="0"),
        sa.Column("latency", sa.Float(), nullable=False, server_default="0"),
        sa.Column("ttft", sa.Float(), nullable=False, server_default="0"),
        sa.CheckConstraint("input_tokens >= 0", name="ck_request_input_tokens_nonneg"),
        sa.CheckConstraint("output_tokens >= 0", name="ck_request_output_tokens_nonneg"),
        sa.CheckConstraint("total_tokens >= 0", name="ck_request_total_tokens_nonneg"),
        sa.CheckConstraint("cost >= 0", name="ck_request_cost_nonneg"),
        sa.CheckConstraint("latency >= 0", name="ck_request_latency_nonneg"),
        sa.CheckConstraint("ttft >= 0", name="ck_request_ttft_nonneg"),
    )
    op.create_index("ix_requests_project_id", "requests", ["project_id"])
    op.create_index("ix_requests_model_id", "requests", ["model_id"])
    op.create_index("ix_requests_provider_id", "requests", ["provider_id"])
    op.create_index("ix_requests_status", "requests", ["status"])

    op.create_table(
        "routing_decisions",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "request_id", pg.UUID(as_uuid=True), sa.ForeignKey("requests.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("candidates", pg.ARRAY(sa.String()), nullable=False, server_default="{}"),
        sa.Column("scores", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("constraints", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("selected", sa.String(255), nullable=False),
        sa.UniqueConstraint("request_id", name="uq_routing_decisions_request_id"),
    )
    op.create_index("ix_routing_decisions_request_id", "routing_decisions", ["request_id"])

    op.create_table(
        "evaluations",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "request_id", pg.UUID(as_uuid=True), sa.ForeignKey("requests.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("evaluator", sa.String(255), nullable=False),
        sa.Column("dimensions", sa.JSON(), nullable=False, server_default="{}"),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.CheckConstraint("score >= 0 AND score <= 1", name="ck_evaluation_score_range"),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_evaluation_confidence_range"),
        sa.UniqueConstraint("request_id", name="uq_evaluations_request_id"),
    )
    op.create_index("ix_evaluations_request_id", "evaluations", ["request_id"])

    op.create_table(
        "benchmarks",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dataset", sa.String(255), nullable=False),
        sa.Column("version", sa.String(32), nullable=False),
        sa.Column("status", sa.String(32), nullable=False, server_default="pending"),
    )

    op.create_table(
        "benchmark_results",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "benchmark_id", pg.UUID(as_uuid=True), sa.ForeignKey("benchmarks.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("model_id", pg.UUID(as_uuid=True), sa.ForeignKey("models.id", ondelete="CASCADE"), nullable=False),
        sa.Column("task", sa.String(255), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column("latency", sa.Float(), nullable=False),
        sa.CheckConstraint("score >= 0", name="ck_benchmark_result_score_nonneg"),
        sa.CheckConstraint("cost >= 0", name="ck_benchmark_result_cost_nonneg"),
        sa.CheckConstraint("latency >= 0", name="ck_benchmark_result_latency_nonneg"),
    )
    op.create_index("ix_benchmark_results_benchmark_id", "benchmark_results", ["benchmark_id"])
    op.create_index("ix_benchmark_results_model_id", "benchmark_results", ["model_id"])

    op.create_table(
        "cache_entries",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "project_id", pg.UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("embedding", pg.ARRAY(sa.Float()), nullable=False),  # actual type set below via raw SQL
        sa.Column("response", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    )
    # sqlalchemy's postgresql dialect module has no first-class `vector` type,
    # so the column above is created as an array and immediately altered to
    # the real pgvector type (this is what pgvector.sqlalchemy.Vector emits).
    op.execute(f"ALTER TABLE cache_entries ALTER COLUMN embedding TYPE vector({EMBEDDING_DIM}) USING embedding::vector({EMBEDDING_DIM})")
    op.create_index("ix_cache_entries_project_id", "cache_entries", ["project_id"])
    op.create_index("ix_cache_entries_expires_at", "cache_entries", ["expires_at"])

    op.create_table(
        "budgets",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "project_id", pg.UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("period", sa.String(32), nullable=False),
        sa.Column("limit", sa.Float(), nullable=False),
        sa.Column("current_spend", sa.Float(), nullable=False, server_default="0"),
        sa.CheckConstraint('"limit" >= 0', name="ck_budget_limit_nonneg"),
        sa.CheckConstraint("current_spend >= 0", name="ck_budget_spend_nonneg"),
    )
    op.create_index("ix_budgets_project_id", "budgets", ["project_id"])

    op.create_table(
        "alerts",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "project_id", pg.UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("type", sa.String(64), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("status", sa.String(32), nullable=False, server_default="active"),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("threshold >= 0", name="ck_alert_threshold_nonneg"),
    )
    op.create_index("ix_alerts_project_id", "alerts", ["project_id"])


def downgrade() -> None:
    op.drop_table("alerts")
    op.drop_table("budgets")
    op.drop_table("cache_entries")
    op.drop_table("benchmark_results")
    op.drop_table("benchmarks")
    op.drop_table("evaluations")
    op.drop_table("routing_decisions")
    op.drop_table("requests")
    op.drop_table("model_metrics")
    op.drop_table("model_prices")
    op.drop_table("api_keys")
    op.drop_table("models")
    op.drop_table("projects")
    op.drop_table("providers")
    op.drop_table("users")
    op.execute("DROP EXTENSION IF EXISTS vector")